### ISSUE TITLE
Not able to add React dependency

### ISSUE THREAD

**Issue by audricganser** [kganser/simpl.js#1]
## Detailed Description

React dependency not showing up in dependency search functionality.

## Expected Behavior

Searching for react in the settings portion of the application should output the react module

## Current Behavior

No react module found

## Possible Solution

N/A

## Steps to Reproduce

1. Create a new app
2. Go to the gear icon 
3. Search for `react` under the dependencies section

**Comment by kganser** [comment]
Install the `react` module from here first:
https://simpljs.com/users/kganser/modules/react

Then it should show up on your console and can be added as a dependency
